#!/usr/bin/env python
#
# Copyright (c) 2025 Authors and contributors
# (see the AUTHORS.rst file for the full list of names)
#
# Released under the GNU Public Licence, v3 or any higher version
# SPDX-License-Identifier: GPL-3.0-or-later

"""Configuration file for the Sphinx documentation builder.

This file does only contain a selection of the most common options. For a full list see
the documentation: http://www.sphinx-doc.org/en/master/config
"""

import tomllib
from datetime import datetime
from pathlib import Path

# -- Path setup --------------------------------------------------------------
import spectrakit

ROOT = Path("../../")

# -- Project information -----------------------------------------------------

with Path(ROOT / "pyproject.toml").open(mode="rb") as fp:
    project_dict = tomllib.load(fp)["project"]

project = project_dict["name"]
author = spectrakit.__authors__
version = spectrakit.__version__
copyright = f"{datetime.now().date().year}, {author}"

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings.
extensions = [
    "sphinx.builders.linkcheck",  # Check that external links are working
    "sphinx.ext.autodoc",  # import the modules you are documenting
    "sphinx_gallery.gen_gallery",  # Generate examples from python files
    "sphinx.ext.viewcode",  # link to source files from docs
    "sphinx.ext.intersphinx",  # generate links to in external projects
    "sphinx.ext.mathjax",  # Render math via JavaScript
    "sphinx.ext.napoleon",  # Support for NumPy and Google style docstrings
    "sphinxcontrib.details.directive",  # details directive for collapsible content
    "sphinx_toggleprompt",  # button to examples to toggle prompts
    "sphinx_tabs.tabs",
]

sphinx_gallery_conf = {
    "copyfile_regex": r".*\.(tpr|trr|xtc)",
    # "default_thumb_file": (ROOT / "docs/static/logo.svg").absolute(),
    "example_extensions": {".py", ".sh"},
    "examples_dirs": ["../../examples"],
    "filename_pattern": r"\.py",
    "gallery_dirs": ["generated_examples"],
    "min_reported_time": 60,
    "prefer_full_module": ["spectrakit"],
    "reference_url": {"spectrakit": None},
    "remove_config_comments": True,
}

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames. You can specify multiple suffix as a list of
# string: note: do not add .ipynb when nbspinx is enabled, otherwise you get the
# "missing title" error
source_suffix = [".rst"]

# The master toctree document.
master_doc = "index"

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns: list[str] = ["get-started/tabs/GALLERY_HEADER.rst"]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "tango"

# -- Options for HTML output -------------------------------------------------

html_theme = "furo"
html_title = "spectrakit"
# html_favicon = "../static/logo.ico"
# html_static_path = ["../static"]

html_theme_options = {
    "navigation_with_keys": True,
    "footer_icons": [
        {
            "name": "GitHub",
            "url": project_dict["urls"]["repository"],
            "html": "",
            "class": "fa-brands fa-github fa-2x",
        },
    ],
    "top_of_page_buttons": [],
    # "light_logo": "logo_MAICOS_light.svg",
    # "dark_logo": "logo_MAICOS_dark.svg",
    "sidebar_hide_name": True,
}

# font-awesome logos
html_css_files = [
    "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/fontawesome.min.css",  # noqa: E501
    "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/solid.min.css",  # noqa: E501
    "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/brands.min.css",  # noqa: E501
]

# -- Options for HTMLHelp output ---------------------------------------------

htmlhelp_basename = "spectrakitdoc"


# -- Extension configuration -------------------------------------------------

# Configuration for intersphinx: refer to the Python standard library
# and other packages used by MAICoS
intersphinx_mapping = {
    "scipy": ("https://docs.scipy.org/doc/scipy/", None),
    "matplotlib": ("https://matplotlib.org/stable/", None),
    "MDAnalysis": ("https://docs.mdanalysis.org/stable/", None),
    "numpy": ("https://numpy.org/doc/stable/", None),
    "python": ("https://docs.python.org/3/", None),
}
